### ISSUE TITLE
Global name root is not defined

### ISSUE THREAD

**Issue by melonyinourfelony** [cskurdal/v-plotter#1]
Hi, I'm trying to use v-plotter.py with svg.py but when I try to run it with a svg file it fails and gives the error "global name root is not defined" I'm trying to run it with python 2.7

**Comment by cskurdal** [comment]
I'd recommend trying with Python 3.

**Comment by melonyinourfelony** [comment]
I also tried with p3 but nothing seems to be changed.
Also does this code need spesific type of svg files?

_________

Somehow i fixed it but it says 


"pi@raspberrypi:~ $ python3 vplotter.py 0 0 -file circle.svg
args: Namespace(c=32.0, r=0.5, setup=False, x=0.0, xml='circle.svg', y=0.0)
Raspberry Pi
{http://www.w3.org/2000/svg}defs {'class': 'ClipPathGroup'}
{http://www.w3.org/2000/svg}defs {'class': 'TextShapeIndex'}
{http://www.w3.org/2000/svg}defs {'class': 'EmbeddedBulletChars'}
{http://www.w3.org/2000/svg}g {}
{http://www.w3.org/2000/svg}g {'class': 'SlideGroup'}
File circle.svg is empty.
"

**Comment by cskurdal** [comment]
I suspect this is due to the minimal support for SVG. This was 7 years ago, but I suspect I only ever had this working with a very simple SVG.
